---
title: "R Notebook"
output: html_notebook
---



```{r}
library(Seurat)
library(tidyverse)
```

```{r}
obj <- readRDS("SCT/intgr_indiv_SCT_harmony/Subclustering/subcluster_annotated_RasV.rds")
```


```{r}
percentage_data <- metadata %>%
  group_by(cell_subtype, condition, batch) %>%
  summarize(count = n(), .groups = 'drop') %>%
  group_by(cell_subtype) %>%
  mutate(total_count = sum(count)) %>%
  ungroup() %>%
  mutate(percentage = (count / total_count) * 100)

# Reorder conditions for plotting
condition_order <- c("ctl", "int", "end")
percentage_data$condition <- factor(percentage_data$condition, levels = condition_order)

# Custom colors for conditions
custom_colors <- c("end" = "#00BA38", "int" = "#619CFF", "ctl" = "#F8766D")

# Create plot
plots <- percentage_data %>%
  ggplot(aes(x = condition, y = percentage, fill = condition)) +
  geom_boxplot(position = position_dodge(width = 0.9), alpha = 0.7) +
  geom_jitter(width = 0.2, alpha = 0.5, size = 0.5) +
  stat_summary(fun = mean, geom = "point", shape = 21, size = 2, color = "black", fill = "white") +
  facet_wrap(~ cell_subtype) +
  theme_bw() +  # Switch to theme_bw() for a better background
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.title = element_text(face = "bold", size = 12),
    axis.text = element_text(size = 10),
    strip.text = element_text(face = "bold", size = 12),
    legend.position = "none",
    panel.grid.major = element_line(color = "grey85"),
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    panel.background = element_rect(fill = "grey98", color = "black"),  # Custom panel background
    panel.border = element_blank(),  # Remove border around the panel
    strip.background = element_rect(fill = "grey90", color = "black")  # Custom facet strip background
  ) +
  labs(
    title = "Relative Abudance of Cell Types per Condition",
    x = "Condition",
    y = "Percentage of Cells"
  ) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_fill_manual(values = custom_colors)  # Apply custom colors







print(plots)
ggsave("cell_subtype_abudance_relative_boxplot.pdf", plot = plots, device = "pdf", dpi = 300, width = 10, height = 8)


```

